name: undefined
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_facebook_auth: ^6.2.0
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  iconly: ^1.0.1
  icons_plus: ^5.0.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
