// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFWRac07lESQpXxnYN1mxPLRiPN-WEi0',
    appId: '1:362156177610:web:e915498a74075416ea9c33',
    messagingSenderId: '362156177610',
    projectId: 'undefined-98c49',
    authDomain: 'undefined-98c49.firebaseapp.com',
    storageBucket: 'undefined-98c49.appspot.com',
    measurementId: 'G-Q0HW0NXYL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASV81h7xtaXyOo5GUw2Ls6opz6enSMqY8',
    appId: '1:362156177610:android:62a3abc50bf469feea9c33',
    messagingSenderId: '362156177610',
    projectId: 'undefined-98c49',
    storageBucket: 'undefined-98c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpSX07EUex5ezm-xm1tLesccLkVGRHo58',
    appId: '1:362156177610:ios:7f9bce219967a23cea9c33',
    messagingSenderId: '362156177610',
    projectId: 'undefined-98c49',
    storageBucket: 'undefined-98c49.appspot.com',
    iosBundleId: 'com.example.undefined',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpSX07EUex5ezm-xm1tLesccLkVGRHo58',
    appId: '1:362156177610:ios:7f9bce219967a23cea9c33',
    messagingSenderId: '362156177610',
    projectId: 'undefined-98c49',
    storageBucket: 'undefined-98c49.appspot.com',
    iosBundleId: 'com.example.undefined',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFWRac07lESQpXxnYN1mxPLRiPN-WEi0',
    appId: '1:362156177610:web:bb97a36c411d0d9bea9c33',
    messagingSenderId: '362156177610',
    projectId: 'undefined-98c49',
    authDomain: 'undefined-98c49.firebaseapp.com',
    storageBucket: 'undefined-98c49.appspot.com',
    measurementId: 'G-BL8RBSVK1C',
  );
}
